### ISSUE TITLE
Breaking change in latest commit

### ISSUE THREAD

**Issue by RobertBlakeAnderson** [swri-robotics/marti_common#738]
On the `master` branch:

The [latest commit](https://github.com/swri-robotics/marti_common/commit/3e3e33251ac357a9d728fe6aea2b3821ff65b645) causes build errors for us. This is caused by the change of #include `<proj_api.h>` to `#include <proj.h>`. The old name is what we have in `/usr/include` on our machines.

**Comment by danthony06** [comment]
@RobertBlakeAnderson Unfortunately, I'm in a bit of a catch-22 on this. Before I made the breaking change, I made a tag called `melodic-eol` because I knew it would break with older versions of `PROJ`. The rationale for making it is we have other users that are pushing forward with newer versions of `PROJ` and the current implementation works with Noetic, which is the only non-EOL ROS 1 distribution at this point. Unfortunately, the API changes with the new version of `PROJ` are not easy to work around.

Since I haven't bloomed these changes, I assume you're building from source? If so, can you keep using the `melodic-eol` branch, or do you really want to keep using our head changes?
